name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Cache dependencies
      id: pnpm-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Prepare Dummy Secrets
      shell: bash
      run: |
        cat .github/actions/setup/android_dummy_secret.xml > example/android/app/src/main/res/values/secret.xml
        echo "NAVER_CLIENT_ID = dummy" > example/ios/Secret.xcconfig
