packages:
  - example
  - docs

catalog:
  '@babel/core': ^7.28.4
  '@babel/runtime': ^7.28.4
  '@biomejs/biome': ^2.2.3
  '@react-native-community/cli': 19.0.0
  '@react-native-community/cli-platform-android': 19.0.0
  '@react-native-community/cli-platform-ios': 19.0.0
  '@react-native/babel-preset': 0.80.0
  '@react-native/metro-config': 0.80.0
  '@react-native/new-app-screen': 0.80.0
  '@react-native/typescript-config': 0.80.0
  '@tailwindcss/postcss': ^4.1.13
  '@types/node': ^20.19.13
  '@types/react': ^19
  '@types/react-dom': ^19
  '@types/react-test-renderer': ^19
  next: ^16.0.3
  react: ^19.2.0
  react-dom: ^19.2.0
  react-native: 0.80.0
  react-test-renderer: ^19
  tailwindcss: ^4.1.13
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver

nodeLinker: hoisted

publicHoistPattern:
- "react-native"
- "@react-native/codegen"
- "@react-native/gradle-plugin"
