packages:
  - example
  - docs

shamefullyHoist: true

catalog:
  '@babel/core': ^7.28.4
  '@babel/runtime': ^7.28.4
  '@biomejs/biome': ^2.2.2
  '@react-native-community/cli': 19.0.0
  '@react-native-community/cli-platform-android': 19.0.0
  '@react-native-community/cli-platform-ios': 19.0.0
  '@react-native/babel-preset': 0.80.0
  '@react-native/metro-config': 0.80.0
  '@react-native/new-app-screen': 0.80.0
  '@react-native/typescript-config': 0.80.0
  '@tailwindcss/postcss': ^4
  '@types/node': ^20
  '@types/react': 19.1.0
  '@types/react-dom': ^19
  '@types/react-test-renderer': ^19.1.0
  react: 19.1.0
  react-native: 0.80.0
  react-test-renderer: 19.1.0
  tailwindcss: ^4
  typescript: 5.3.3

onlyBuiltDependencies:
  - lefthook
  - unrs-resolver
