export enum Gravity {
  NO_GRAVITY = 0,
  AXIS_SPECIFIED = 1,
  AXIS_PULL_BEFORE = 2,
  AXIS_PULL_AFTER = 4,
  AXIS_X_SHIFT = 0,
  AXIS_Y_SHIFT = 4,
  TOP = 48,
  BOTTOM = 80,
  LEFT = 3,
  RIGHT = 5,
  CENTER_VERTICAL = 16,
  CENTER_HORIZONTAL = 1,
}
