export enum LayerGroup {
  LAYER_GROUP_BUILDING = 'BUILDING',
  LAYER_GROUP_TRAFFIC = 'TRAFFIC',
  LAYER_GROUP_TRANSIT = 'TRANSIT',
  LAYER_GROUP_BICYCLE = 'BICYCLE',
  LAYER_GROUP_MOUNTAIN = 'MOUNTAIN',
  LAYER_GROUP_CADASTRAL = 'CADASTRAL',
}
