/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 * <p>
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsJavaInterface.js
 */

import android.view.View;

import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;

import androidx.annotation.Nullable;

public interface RNCNaverMapViewManagerInterface<T extends View> {
    void setMapType(T view, @Nullable String value);

    void setLayerGroups(T view, @Nullable ReadableArray value);

    void setIsIndoorEnabled(T view, boolean value);

    void setIsNightModeEnabled(T view, boolean value);

    void setIsLiteModeEnabled(T view, boolean value);

    void setLightness(T view, double value);

    void setBuildingHeight(T view, double value);

    void setSymbolScale(T view, double value);

    void setSymbolPerspectiveRatio(T view, double value);

    void setCenter(T view, @Nullable ReadableMap value);

    void setMapPadding(T view, @Nullable ReadableMap value);

    void animateToCoordinate(T view, double latitude, double longitude);

    void animateToBound(T view, String encodedJsonString);
}
